/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiEngineRouteImport } from './routes/api/engine'
import { Route as ApiJobsRouteImport } from './routes/api/jobs'
import { Route as ApiProbeRouteImport } from './routes/api/probe'
import { Route as ApiJobsJobIdRouteImport } from './routes/api/jobs/$jobId'
import { Route as ApiJobsJobIdFileRouteImport } from './routes/api/jobs/$jobId/file'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEngineRoute = ApiEngineRouteImport.update({
  id: '/api/engine',
  path: '/api/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsRoute = ApiJobsRouteImport.update({
  id: '/api/jobs',
  path: '/api/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProbeRoute = ApiProbeRouteImport.update({
  id: '/api/probe',
  path: '/api/probe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsJobIdRoute = ApiJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => ApiJobsRoute,
} as any)
const ApiJobsJobIdFileRoute = ApiJobsJobIdFileRouteImport.update({
  id: '/file',
  path: '/file',
  getParentRoute: () => ApiJobsJobIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/engine': typeof ApiEngineRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/api/probe': typeof ApiProbeRoute
  '/api/jobs/$jobId': typeof ApiJobsJobIdRouteWithChildren
  '/api/jobs/$jobId/file': typeof ApiJobsJobIdFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/engine': typeof ApiEngineRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/api/probe': typeof ApiProbeRoute
  '/api/jobs/$jobId': typeof ApiJobsJobIdRouteWithChildren
  '/api/jobs/$jobId/file': typeof ApiJobsJobIdFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/engine': typeof ApiEngineRoute
  '/api/jobs': typeof ApiJobsRouteWithChildren
  '/api/probe': typeof ApiProbeRoute
  '/api/jobs/$jobId': typeof ApiJobsJobIdRouteWithChildren
  '/api/jobs/$jobId/file': typeof ApiJobsJobIdFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/engine'
    | '/api/jobs'
    | '/api/probe'
    | '/api/jobs/$jobId'
    | '/api/jobs/$jobId/file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/engine'
    | '/api/jobs'
    | '/api/probe'
    | '/api/jobs/$jobId'
    | '/api/jobs/$jobId/file'
  id:
    | '__root__'
    | '/'
    | '/api/engine'
    | '/api/jobs'
    | '/api/probe'
    | '/api/jobs/$jobId'
    | '/api/jobs/$jobId/file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiEngineRoute: typeof ApiEngineRoute
  ApiJobsRoute: typeof ApiJobsRouteWithChildren
  ApiProbeRoute: typeof ApiProbeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/engine': {
      id: '/api/engine'
      path: '/api/engine'
      fullPath: '/api/engine'
      preLoaderRoute: typeof ApiEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs': {
      id: '/api/jobs'
      path: '/api/jobs'
      fullPath: '/api/jobs'
      preLoaderRoute: typeof ApiJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/probe': {
      id: '/api/probe'
      path: '/api/probe'
      fullPath: '/api/probe'
      preLoaderRoute: typeof ApiProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/$jobId': {
      id: '/api/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/api/jobs/$jobId'
      preLoaderRoute: typeof ApiJobsJobIdRouteImport
      parentRoute: typeof ApiJobsRoute
    }
    '/api/jobs/$jobId/file': {
      id: '/api/jobs/$jobId/file'
      path: '/file'
      fullPath: '/api/jobs/$jobId/file'
      preLoaderRoute: typeof ApiJobsJobIdFileRouteImport
      parentRoute: typeof ApiJobsJobIdRoute
    }
  }
}

interface ApiJobsJobIdRouteChildren {
  ApiJobsJobIdFileRoute: typeof ApiJobsJobIdFileRoute
}

const ApiJobsJobIdRouteChildren: ApiJobsJobIdRouteChildren = {
  ApiJobsJobIdFileRoute: ApiJobsJobIdFileRoute,
}

const ApiJobsJobIdRouteWithChildren = ApiJobsJobIdRoute._addFileChildren(
  ApiJobsJobIdRouteChildren,
)

interface ApiJobsRouteChildren {
  ApiJobsJobIdRoute: typeof ApiJobsJobIdRouteWithChildren
}

const ApiJobsRouteChildren: ApiJobsRouteChildren = {
  ApiJobsJobIdRoute: ApiJobsJobIdRouteWithChildren,
}

const ApiJobsRouteWithChildren =
  ApiJobsRoute._addFileChildren(ApiJobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiEngineRoute: ApiEngineRoute,
  ApiJobsRoute: ApiJobsRouteWithChildren,
  ApiProbeRoute: ApiProbeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
